# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"               # package.json 放的位置
    schedule:
      interval: "daily"         # daily | weekly | monthly
      day: "monday"
    open-pull-requests-limit: 10
    # optional: 分組、忽略規則
    # allow / ignore / reviewers / labels etc.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
